namespace: crm
records:
  Settings:
  - values:
      QuoteExpirationDays: "30"
      QuoteNextNumber: "1"
      OpportunityCloseDateDays: "30"
      OpportunityProbability: "10"
      OpportunityForecaseCategory: "Pipeline"
      OpportunityStagename: "Qualification"
      ContractNextNumber: "1"
      ContractDefaultTime: "12"
      CaseNextNumber: "1"
      SolutionNextNumber: "1"
      ScoreBudget: "1"
      ScoreAuthority: "1"
      ScoreNeed: "1"
      ScoreTimescale: "1"
      ScoreTurnover: "0"
      ScoreYearsInBusiness: "1"
      ScoreSource: "0"
      ScoreProductKnowlege: "0"
      ScoreTechnicalDepth: "0"
      ScoreCompetition: "1"
      ScoreCriticality: "1"
      ScoreRepeatPurchase: "1"
