# List of loggable service actions

resource: system:application
service: application

# Default sensitivity for actions
defaultActionSeverity: notice

# default severity for errors
defaultErrorSeverity: error

import:
  - github.com/cortezaproject/corteza/server/system/types

props:
  - name: application
    type: "*types.Application"
    fields: [ name, ID ]
  - name: new
    type: "*types.Application"
    fields: [ name, ID ]
  - name: update
    type: "*types.Application"
    fields: [ name, ID ]
  - name: filter
    type: "*types.ApplicationFilter"
    fields: [ query, name, deleted, sort ]

actions:
  - action: search
    log: "searched for applications"
    severity: info

  - action: reorder
    log: "reordered applications"

  - action: lookup
    log: "looked-up for a {{application}}"
    severity: info

  - action: create
    log: "created {{application}}"

  - action: update
    log: "updated {{application}}"

  - action: delete
    log: "deleted {{application}}"

  - action: undelete
    log: "undeleted {{application}}"

  - action: flagManage
    log: "managed flags for application {{application}}"

  - action: flagManageGlobal
    log: "managed global flags for application {{application}}"

errors:
  - error: notFound
    message: "application not found"
    severity: warning

  - error: invalidID
    message: "invalid ID"
    severity: warning

  - error: staleData
    message: "stale data"
    severity: warning

  - error: notAllowedToRead
    message: "not allowed to read this application"
    log: "failed to read {{application.name}}; insufficient permissions"

  - error: notAllowedToSearch
    message: "not allowed to search or list applications"
    log: "failed to search or list applications; insufficient permissions"

  - error: notAllowedToCreate
    message: "not allowed to create applications"
    log: "failed to create application; insufficient permissions"

  - error: notAllowedToUpdate
    message: "not allowed to update this application"
    log: "failed to update {{application.name}}; insufficient permissions"

  - error: notAllowedToDelete
    message: "not allowed to delete this application"
    log: "failed to delete {{application.name}}; insufficient permissions"

  - error: notAllowedToUndelete
    message: "not allowed to undelete this application"
    log: "failed to undelete {{application.name}}; insufficient permissions"

  - error: notAllowedToManageFlag
    message: "not allowed to manage flags for applications"
    log: "failed to manage flags {{application.name}}; insufficient permissions"

  - error: notAllowedToManageFlagGlobal
    message: "not allowed to manage global flags for applications"
    log: "failed to manage global flags {{application.name}}; insufficient permissions"
