rbac:
  resource: { references: [] }

  operations:
    grant:
      description: Manage Compose permissions

    settings.read:
      description: Read settings
    settings.manage:
      description: Manage settings

    namespace.create:
      description: Create namespace
    namespaces.search:
      description: List, search or filter namespaces
